### ISSUE TITLE
In the file named 'comm_net.py'

### ISSUE THREAD

**Issue by PeiYingjun** [Coac/CommNet-BiCnet#1]
At row 104, the code is ''h = tf.slice(H, [j, 0], [1, HIDDEN_VECTOR_LEN]) ''
shouldn't it be h = tf.slice(H, [0,j,0],[-1, 1, HIDDEN_VECTOR_LEN]) ?

**Comment by PeiYingjun** [comment]
seems that the dimension of batch_size is missing

**Comment by Coac** [comment]
It should be fixed now b7a1e3184c9881c9957d0cfe3b160797a6bd7cd6
